function alldata = MoreColor(nms)
% Take human colorfulness data and compute colorfulness ratings
% as how many times a given color was picked as more colorful
% than the other option divided by how many times that color was shown

dataDir = '../../data/identification/';
resultsDir = "../../results/identification/"; 
out_dir = "../../figures/figs3_4/";

if ~nargin
    nms = {'MoreColor_2.csv', 'MoreColor_3.csv'};
end

redVals = [224,141,190,122,123,86,66,50,144,95,212,136,186,113];
greenVals = [152,84,170,102,186,114,188,115,172,102,151,82,166,102];
blueVals = [155,97,106,52,128,72,186,119,222,149,208,139,187,109];
barGrey = [150, 132, 153];

barCData = [redVals(:), greenVals(:), blueVals(:)];

% % warm, bright, color
stimID = [...
    1, 1, 1;...
    1, 0, 1;...
    1, 1, 2;...
    1, 0, 2;...
    0, 1, 3;...
    0, 0, 3;...
    0, 1, 4;...
    0, 0, 4;...
    0, 1, 5;...
    0, 0, 5;...
    1, 1, 6;...
    1, 0, 6;...
    0, 1, 7;...
    0, 0, 7;...
    ];
chroma = [...
    "warm";...
    "warm";...
    "warm";...
    "warm";...
    "cool";...
    "cool";...
    "cool";...
    "cool";...
    "cool";...
    "cool";...
    "warm";...
    "warm";...
    "cool";...
    "cool"];
lumVal = [...
    "bright";...
    "dim";...
    "bright";...
    "dim";...
    "bright";...
    "dim";...
    "bright";...
    "dim";...
    "bright";...
    "dim";...
    "bright";...
    "dim";...
    "bright";...
    "dim"];
hue = [...
    "red";...
    "red";...
    "gold";...
    "gold";...
    "green";...
    "green";...
    "turq";...
    "turq";...
    "blue";...
    "blue";...
    "pink";...
    "pink";...
    "grey";...
    "grey"];


allColorsChosen = [];
    allColors = [];

% figure;
for n = 1:length(nms)
    
    nm = nms{n};
    nm = [dataDir, nm];

    opts = detectImportOptions(nm, ...
        'Delimiter', ',', ...
        'VariableNamingRule', 'preserve');
    data = readtable(nm, opts);
    didx = 1:length(data.subject_number);

    answers = {data.Answer_answer{didx}};
    colors1 = {data.Answer_Choice1ColorIndex{didx}};
    colors2 = {data.Answer_Choice2ColorIndex{didx}};
    workers = data.subject_number(didx);
    
    nworker = length(answers);
    
    
    for w = 1:nworker
        c1 = str2num(colors1{w});
        c2 = str2num(colors2{w});
        colors = [c1(:),c2(:)];
        cidx = answers{w};
        cidx = str2num(replace(cidx, 'idx', '')); %#ok<*ST2NM>
        
        if all(cidx == cidx(1))
            disp(workers{w});
        end
        
        allColors = [allColors; colors(:)];
        chosen = diag(colors(:, cidx));
        allColorsChosen = [allColorsChosen; chosen(:)]; %#ok<AGROW>
%         plot(hist(chosen, 1:14), 'k+');
%         hold on;
    end
end
% figure;
% histogram(allColorsChosen, 1:14);


timesChosen = hist(allColorsChosen, 1:14);
timesShown =  hist(allColors, 1:14);

h = figure;
t = tiledlayout(8, 14,'TileSpacing','Compact');
nexttile([7, 14]);

for s = 1:14
    b = bar(s, timesChosen(s)/timesShown(s));
    b.FaceColor = barCData(s,:)./255;
    hold on;
end
set(gca, 'XTick', 1:14);
% legend('color chosen', 'shape chosen');
title('More colorful')

xlim([0.5, 14.5]);
yline(0.5, 'k--', 'LineWidth', 1);



% Compute probability of choosing each color
k = timesChosen(:);
n = timesShown(:);
pColorProb = k ./ n; % probability of choosing each color
stimNumbered = (1:1:14)'; 
probTable = table(stimNumbered, pColorProb);
writetable(probTable, resultsDir + "morecolor_probs.csv");

% Compute 95% confidence interval, normal approximation
z = 1.96;                
se = z*sqrt(pColorProb.*(1-pColorProb) ./ n);
lo = max(0, pColorProb - se);
hi = min(1, pColorProb + se);

ccc= [1,1,1];
wid = 3;
f = figure;
f.Units = "inches";
f.Position = [1 1 2 2];

pax = polaraxes('Parent', f); %, 'Position', [0.1, 0.2, 0.8, 0.7]);

theta = deg2rad(0:60:360);
bigtheta = deg2rad(0:360);
s1 = 1:2:12;
s1(end+1) = s1(1);
s2 = s1 + 1;
p = polarplot(theta, pColorProb(s1), 'k--', 'LineWidth', 1.5);
hold on;
p = polarplot(theta, pColorProb(s2), 'k-', 'LineWidth', 1.5);
set(gca, 'ThetaTickLabel', {});
set(gca, 'RLim', [0, 0.9]);
set(gca, 'RTick', [0, .25, 0.5]); 

theta = deg2rad(0:60:359);
for s = 1:length(theta)
    s1 = 2*(s)-1;
    s2 = s1+1;

    polarplot(pax, theta(s), pColorProb(s1), 'ko', 'MarkerFaceColor',  barCData(s1,:)./255, 'MarkerEdgeColor', 'none', 'MarkerSize', 6);
    polarplot(pax,[theta(s) theta(s)], [lo(s1) hi(s1)], '-', ...
        'LineWidth', 1.5, 'Color', barCData(s1,:)./255);

    polarplot(pax,theta(s), pColorProb(s2), 'ko', 'MarkerFaceColor',  barCData(s2,:)./255, 'MarkerEdgeColor', 'none', 'MarkerSize', 6);
    polarplot(pax,[theta(s) theta(s)], [lo(s2) hi(s2)], '-', ...
        'LineWidth', 1.5, 'Color', barCData(s2,:)./255);

fontsize(10,"points");

exportgraphics(f, out_dir + "more_colorful_polar_identification.svg",Units="inches", ...
    Width=2,Height=2,Resolution=300);
exportgraphics(f,out_dir + "more_colorful_polar_identification.png",Units="inches", ...
    Width=2,Height=2,Resolution=300);

end
