function result = optdlg(options, dlg_nm)

% function optdlg(options)
% Example options:
% opts = {{'num','histlim','Histogram axis limits','5'},...
% {'num','numbins','# histogram bins','20'},...
% {'num','dotsize','marker size','6'},...
% {'tf','pruning','Remove pruned data','f'},...
% {'tf','doclassify','Classify data','t'}};

if strcmp(options,'#FigKeyPressFcn'),
	QuestFig=get(0,'CurrentFigure');
	AsciiVal= abs(get(QuestFig,'CurrentCharacter'));
	if ~isempty(AsciiVal),
		if AsciiVal==32 | AsciiVal==13 | AsciiVal==3,
			uiresume(QuestFig);
		end %if AsciiVal
	end %if ~isempty
	return;
end

if nargin < 2
	dlg_nm = 'Options';
end;

fontheight = 9;
itemheight = 20;
itemwidth = 250;
itemspace = 6;
boxwid = 200;
labelmargin = 25;

numopt = length(options);
kind = {};
name = {};
desc = {};
defval = {};

for o = 1:numopt
	curropt = options{o};
	kind{o} =  curropt{1};
	name{o} = curropt{2};
	desc{o} = curropt{3};
	defval{o} = curropt{4};
end;

% how big to make the figure
itemallow = itemspace+itemheight;
fht = itemallow * numopt + 50;  % for continue and cancel buttons
fwid = itemwidth + boxwid;

screen = get(0, 'ScreenSize');
width = screen(3);
height = screen(4);
xcent = width/2;
ycent = height/2;

fbot = ycent - fht/2;
fleft = xcent - fwid/2;

% hitting close box is like cancel
closeFunction = ['set(gcf,''UserData'',''Cancel'');uiresume;'];

optfig = figure('MenuBar','none', ...
	'CloseRequestFcn', closeFunction,...
	'NumberTitle','off', ...
	'Name',dlg_nm, ...
	'Position',[fleft fbot fwid fht], ...
	'Tag','optfig', ...
	'KeyPressFcn'     ,'optdlg #FigKeyPressFcn;', ...
	'Units','pixels',...
	'WindowStyle','modal');

y = (fht-10) - itemheight;
x = 5;
xbox = 2*x + boxwid;

item = {};

for o = 1:numopt
	switch kind{o}
		case 'num',
			% text(num) box
			lbl = uicontrol('Parent',optfig, ...
				'Units','pixels', ...
				'FontSize',fontheight, ...
				'HorizontalAlignment','left', ...
				'Position',[xbox y itemwidth-labelmargin itemheight], ...
				'String',desc{o},...
				'Style','Text', ...
				'Tag','lbl');
			etxt = uicontrol('Parent',optfig, ...
				'CallBack','',...
				'Units','pixels', ...
				'BackgroundColor',[1 1 1], ...
				'FontSize',fontheight, ...
				'HorizontalAlignment','left', ...
				'Position',[x y boxwid itemheight], ...
				'String',defval{o}, ...
				'Style','edit', ...
				'Tag','etxt');
			item{o} = etxt;
		case 'tf',
			% logical - radio button
			btn = uicontrol('Parent',optfig, ...
				'CallBack','',...
				'Units','pixels', ...
				'FontSize',fontheight, ...
				'Position',[x y itemwidth itemheight], ...
				'String',desc{o},...
				'Style','CheckBox', ...
				'Tag','btn',...
				'Value',0);
			item{o} = btn;

			def = defval{o};
			if strcmp(def,'t') | strcmp(def,'1')
				set(btn,'Value',1);
			end;
		case 'string',
			% string - edit text
			lbl = uicontrol('Parent',optfig, ...
				'Units','pixels', ...
				'FontSize',fontheight, ...
				'HorizontalAlignment','left', ...
				'Position',[xbox y itemwidth-labelmargin itemheight], ...
				'String',desc{o},...
				'Style','Text', ...
				'Tag','lbl');
			etxt = uicontrol('Parent',optfig, ...
				'CallBack','',...
				'Units','pixels', ...
				'BackgroundColor',[1 1 1], ...
				'FontSize',fontheight, ...
				'HorizontalAlignment','left', ...
				'Position',[x y boxwid itemheight], ...
				'String',defval{o}, ...
				'Style','edit', ...
				'Tag','etxt');
			item{o} = etxt;
		case {'strmenu','nummenu'},
			% menu items
			lbl = uicontrol('Parent',optfig, ...
				'Units','pixels', ...
				'FontSize',fontheight, ...
				'HorizontalAlignment','left', ...
				'Position',[xbox y itemwidth-labelmargin itemheight], ...
				'String',desc{o},...
				'Style','Text', ...
				'Tag','lbl');

			if iscell(defval{o}{1})
				menustr = defval{o}{1};
				menuval = str2num(defval{o}{2});
			else
				menustr = defval{o};
				menuval = 1;
			end;
			pmenu = uicontrol('Parent',optfig, ...
				'CallBack','',...
				'Units','pixels', ...
				'BackgroundColor',[1 1 1], ...
				'FontSize',fontheight, ...
				'HorizontalAlignment','left', ...
				'Position',[x y+10 boxwid itemheight-10], ...
				'String',menustr, ...
				'Value',menuval, ...
				'Style','popupmenu', ...
				'Tag','popup');
			item{o} = pmenu;
		otherwise,
			close;
			error(['Unknown item type ',kind{o}]);
	end;
	y = y - (itemheight + itemspace);


end;  % creating user ui items

y = y - 10;

cancelbtn = uicontrol('Parent',optfig, ...
	'CallBack','set(gcf,''UserData'',''Cancel'');uiresume',...
	'Units','pixels', ...
	'FontSize',9,...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ForegroundColor',[0 0 0],...
	'HorizontalAlignment','left', ...
	'Position',[x y 50 20], ...
	'String','Cancel', ...
	'Tag','cancelbtn');

contbtn = uicontrol('Parent',optfig, ...
	'CallBack','set(gcf,''UserData'',''Continue'');uiresume',...
	'Units','pixels', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ForegroundColor',[0 0 0],...
	'HorizontalAlignment','left', ...
	'Position',[fwid-100 y 75 20], ...
	'String','Continue', ...
	'Tag','contbtn');


set(gcf,'Units','normalized');
drawnow;
pause(0.2);
uiwait;

if strcmp(get(gcf,'UserData'),'Cancel');
	% 	disp('Cancel');
	result = [];
else
	result = [];
	% assign the variables;
	for o = 1:numopt
		result = [result; get(item{o}, 'Value')];
		switch kind{o},
			case 'num',
				% number in text field
				currval = str2num(get(item{o},'String'));
				assignin('caller',name{o},currval);
			case 'string',
				% string in text field
				currval = get(item{o},'String');
				assignin('caller',name{o},currval);
			case 'tf',
				% logical in radio button
				currval = get(item{o},'Value');
				assignin('caller',name{o},currval);
			case 'strmenu',
				% menu of string choices
				itemstr = get(item{o},'String');
				itemidx = get(item{o},'Value');
				currval = itemstr{itemidx};
				assignin('caller',name{o},currval);
			case 'nummenu',
				% menu of numerical choices
				itemstr = get(item{o},'String');
				itemidx = get(item{o},'Value');
				currval = itemstr{itemidx};
				assignin('caller',name{o},str2num(currval));
		end;
	end;
end;

set(gcf, 'CloseRequestFcn', 'closereq;');
close(gcf);
drawnow;
